#pragma once

// Drive
#define PIGEON_IMU 0
#define DRIVE_LEFT_MASTER 1
#define DRIVE_LEFT_SLAVE 2
#define DRIVE_RIGHT_MASTER 3
#define DRIVE_RIGHT_SLAVE 4
// Elevator
#define ELEVATOR_MASTER 13
#define ELEVATOR_SLAVE 11
// Ball Intake
#define BALL_INTAKE_MASTER 9
#define BALL_INTAKE_SLAVE 10
// Outrigger
#define OUTRIGGER_ARM_MASTER 11
#define OUTRIGGER_ARM_SLAVE 12
#define OUTRIGGER_WHEEL 13
#define FLIPPER 14
#define HATCH_SERVO 0
#define LOCK_SERVO 1
#define CAMERA_SERVO 2

#define CONFIG_TIMEOUT 500
