#pragma once

#define PIGEON_IMU 0
#define DRIVE_LEFT_MASTER 1
#define DRIVE_LEFT_SLAVE 2
#define DRIVE_RIGHT_MASTER 3
#define DRIVE_RIGHT_SLAVE 4
#define ELEVATOR_MASTER 5
#define ELEVATOR_SLAVE_ONE 6
#define ELEVATOR_SLAVE_TWO 7
#define ELEVATOR_SLAVE_THREE 8
#define BALL_INTAKE_MASTER 9
#define BALL_INTAKE_SLAVE 10
#define OUTRIGGER_ARM_MASTER 11
#define OUTRIGGER_ARM_SLAVE 12
#define OUTRIGGER_WHEEL 13
#define FLIPPER 14
#define HATCH_SERVO 0
#define HATCH_SERVO_LOWER 700
#define HATCH_SERVO_UPPER 1700
#define FLIPPER_LOWER 2.0
#define FLIPPER_UPPER 34.0

#define ELEVATOR_LOWER_POSITION 0.0
#define ELEVATOR_HIGHER_POSITION 1000.0